CC = gcc

CFLAGS = -Wall -Wextra -pedantic -std=c99

LIB_NAME = libapp_data.a

SRC_FILES = app_data_generated.c
OBJ_FILES = $(SRC_FILES:.c=.o)

all: $(LIB_NAME)

$(LIB_NAME): $(OBJ_FILES)
	@echo "Création de la librairie statique $(LIB_NAME)"
	ar rcs $(LIB_NAME) $(OBJ_FILES)

%.o: %.c
	@echo "Compilation de $<"
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	@echo "Nettoyage des fichiers intermédiaires"
	rm -f $(OBJ_FILES) $(LIB_NAME)

.PHONY: all clean
